global:
  # how frequently to scrape targets by default
  scrape_interval: 15s

scrape_configs:
  - job_name: entry-task
    scrape_interval: 10s
    static_configs:
      - targets:
          - localhost:8080