global:
  # how frequently to scrape targets by default
  scrape_interval: 30s

scrape_configs:
  - job_name: http-server
    scrape_interval: 15s
    static_configs:
      - targets:
          - localhost:8080
  - job_name: node-exporter
    scrape_interval: 15s
    static_configs:
      - targets:
          - localhost:9100
